"""Capabilities consumed by execution, without a concrete Agent dependency."""

from __future__ import annotations

from collections.abc import AsyncIterator, Iterator
from typing import Any, Protocol

from models import AI, Chunk, Message, ToolCall
from core.agent_runtime.events import AgentEvent


class ModelClient(Protocol):
    """Existing OpenAI-compatible provider boundary; no inheritance required."""

    def invoke(self, messages: list[Message], **kwargs: Any) -> dict[str, Any]: ...
    async def ainvoke(self, messages: list[Message], **kwargs: Any) -> dict[str, Any]: ...
    def stream(self, messages: list[Message], **kwargs: Any) -> Iterator[Chunk]: ...
    def astream(self, messages: list[Message], **kwargs: Any) -> AsyncIterator[Chunk]: ...


class AgentRuntimePort(Protocol):
    session: Any
    options: Any
    context_manager: Any
    run_state: Any
    context_transform: Any
    @property
    def llm(self) -> ModelClient: ...
    @property
    def max_turns(self) -> int: ...
    @property
    def max_tokens(self) -> int: ...

    @property
    def temperature(self) -> float: ...

    def enter_run(self) -> None: ...
    def exit_run(self) -> None: ...
    def publish(self, event: AgentEvent) -> None: ...
    def deadline(self) -> float | None: ...
    def check_deadline(self, deadline: float | None) -> None: ...
    def prepare_messages(self) -> list[Message]: ...
    def tools_payload(self) -> list[dict[str, Any]] | None: ...
    def add_session_message(self, message: Message) -> None: ...
    def execute_tool_calls(self, tool_calls: list[ToolCall]) -> list[Message]: ...
    def should_stop_after_tool_calls(self, results: list[Message]) -> bool: ...
    def parse_invoke_response(self, data: dict[str, Any]) -> tuple[AI, list[ToolCall]]: ...
