"""Neutral defaults; environment parsing belongs to application configuration."""
DEFAULT_MAX_TURNS = 20
DEFAULT_MAX_TOKENS = 4096
DEFAULT_TEMPERATURE = 0.7
ACTIVE_MESSAGE_LIMIT = 80
HISTORY_MESSAGE_LIMIT = 1000
TIMEOUT = 120.0
AGENT_RUN_TIMEOUT = 0.0
LOG_LEVEL = "INFO"
READ_FILE_MAX_CHARS = 12000
